Team_names = {'Lakers','Suns','Twolves','Pelicans','Nuggets','Kings','Jazz',...
    'Rockets','Grizzlies','Mavs','Blazers','Clippers','Thunder','Spurs',...
    'Warriors','Nets','Knicks','Bucks','Magic','Wizards','Bulls',...
    'Pistons','Pacers','Hornets','Celtics','Hawks','Heat','Raptors','Cavs'}